export const DIVINDADES = [
    { value: '', text: 'Nenhuma divindade' },
    'Aharadak',
    'Allihanna',
    'Arsenal',
    'Azgher',
    'Hyninn',
    'Kallyadranoch',
    'Khalmyr',
    'Lena',
    'Lin-Wu',
    'Marah',
    'Megalokk',
    'Nimb',
    'Oceano',
    'Sszzaas',
    'Tanna-Toh',
    'Tenebra',
    'Thwor',
    'Thyatis',
    'Valkaria',
    'Wynna',
]

export const DIVINDADES_DETAILS = [
    { name: '', energia: '', arma: '', poderes: '' },
    { name: 'Aharadak', energia: 'Negativa', arma: 'Corrente de espinhos', poderes: 'Afinidade com a Tormenta, Percepção Temporal, Rejeição Divina' },
    { name: 'Allihanna', energia: 'Positiva', arma: 'Bordão', poderes: 'Dedo Verde, Descanso Natural, Voz da Natureza' },
    { name: 'Arsenal', energia: 'Negativa', arma: 'Martelo de guerra', poderes: 'Conjurar Arma, Coragem Total, Sangue de Ferro' },
    { name: 'Azgher', energia: 'Positiva', arma: 'Cimitarra', poderes: 'Espada Solar, Habitante do Deserto, Inimigo de Tenebra' },
    { name: 'Hyninn', energia: 'Qualquer', arma: 'Adaga', poderes: 'Farsa do Fingidor, Forma de Macaco, Golpista Divino' },
    { name: 'Kallyadranoch', energia: 'Negativa', arma: 'Lança', poderes: 'Aura de Medo, Escamas Dracônicas, Servos do Dragão' },
    { name: 'Khalmyr', energia: 'Positiva', arma: 'Espada longa', poderes: 'Coragem Total, Dom da Verdade, Espada Justiceira' },
    { name: 'Lena', energia: 'Positiva', arma: '', poderes: 'Ataque Piedoso, Aura Restauradora, Cura Gentil, Curandeira Perfeita' },
    { name: 'Lin-Wu', energia: 'Qualquer', arma: 'Katana', poderes: 'Coragem Total, Kiai Divino, Mente Vazia' },
    { name: 'Marah', energia: 'Positiva', arma: '', poderes: 'Aura de Paz, Palavras de Bondade, Talento Artístico' },
    { name: 'Megalokk', energia: 'Negativa', arma: 'Maça', poderes: 'Olhar Amedrontador, Urro Divino, Voz dos Monstros' },
    { name: 'Nimb', energia: 'Qualquer', arma: '?', poderes: 'Poder Oculto, Sorte dos Loucos, Transmissão da Loucura' },
    { name: 'Oceano', energia: 'Qualquer', arma: 'Tridente', poderes: 'Anfíbio, Arsenal das Profundezas, Mestre dos Mares' },
    { name: 'Sszzaas', energia: 'Negativa', arma: 'Adaga', poderes: 'Astúcia da Serpente, Presas Venenosas, Sangue Ofídico' },
    { name: 'Tanna-Toh', energia: 'Qualquer', arma: 'Bordão', poderes: 'Conhecimento Enciclopédico, Mente Analítica, Voz da Civilização' },
    { name: 'Tenebra', energia: 'Negativa', arma: 'Adaga', poderes: 'Carícia Sombria, Manto da Penumbra, Visão nas Trevas' },
    { name: 'Thwor', energia: 'Qualquer', arma: 'Machado de guerra', poderes: 'Fúria Divina, Olhar Amedrontador, Tropas Duyshidakk' },
    { name: 'Thyatis', energia: 'Positiva', arma: 'Espada longa', poderes: 'Ataque Piedoso, Dom da Imortalidade, Dom da Profecia, Dom da Ressurreição' },
    { name: 'Valkaria', energia: 'Positiva', arma: 'Mangual', poderes: 'Armas da Ambição, Coragem Total, Liberdade Divina' },
    { name: 'Wynna', energia: 'Qualquer', arma: 'Adaga', poderes: 'Bênção do Mana, Centelha Mágica, Escudo Mágico, Teurgista Místico' }
]