export const ORIGENS = [
    'Acólito',
    'Amigo dos Animais',
    'Amnésico',
    'Aristocrata',
    'Artesão',
    'Artista',
    'Assistente de Laboratório',
    'Batedor',
    'Capanga',
    'Charlatão',
    'Circense',
    'Criminoso',
    'Curandeiro',
    'Eremita',
    'Escravo',
    'Estudioso',
    'Fazendeiro',
    'Forasteiro',
    'Gladiador',
    'Guarda',
    'Herdeiro',
    'Herói Camponês',
    'Marujo',
    'Mateiro',
    'Membro de Guilda',
    'Mercador',
    'Minerador',
    'Nômade',
    'Pivete',
    'Refugiado',
    'Seguidor',
    'Selvagem',
    'Soldado',
    'Taverneiro',
    'Trabalhador',
]