export const RACAS = [
    'Humano',
    'Anão',
    'Dahllan',
    'Elfo',
    'Goblin',
    'Lefou',
    'Minotauro',
    'Qareen',
    'Golem',
    'Hynne',
    'Kliren',
    'Medusa',
    'Osteon',
    'Sereia/tritão',
    'Sílfide',
    'Suraggel',
    'Trog',
]

export const RACAS_DETAIL = [
    { name: 'Humano', attrAjust: '+2 em Três Atributos Diferentes', habilidades: 'Versátil' },
    { name: 'Anão', attrAjust: 'Constituição +4, Sabedoria +2, Destreza –2', habilidades: 'Conhecimento das Rochas, Devagar e Sempre, Duro como pedra, Tradição de Heredrimm' },
    { name: 'Dahllan', attrAjust: 'Sabedoria +4, Destreza +2, Inteligência –2', habilidades: 'Amiga das plantas, Armaura de Allihana, Empatia selvagem' },
    { name: 'Elfo', attrAjust: 'Inteligência +4, Destreza +2, Constituição –2', habilidades: 'Graça de Glórienn, Herança Feérica, Sentidos Élficos' },
    { name: 'Goblin', attrAjust: 'Destreza +4, Inteligência +2, Carisma –2', habilidades: 'Engenhoso, Espelunqueiro, Peste esguia, Rato das ruas' },
    { name: 'Lefou', attrAjust: '+2 em Três Atributos Diferentes (exceto Carisma), Carisma –2', habilidades: 'Cria da tormenta, Deformidade' },
    { name: 'Minotauro', attrAjust: 'Força +4, Constituição +2, Sabedoria –2', habilidades: 'Chifres, Faro, Medo de altura' },
    { name: 'Qareen', attrAjust: 'Carisma +4, Inteligência +2, Sabedoria –2', habilidades: 'Desejos, Resistência elemental, Tatuagem mística' },
    { name: 'Golem', attrAjust: 'Força +4, Constituição +2, Carisma –2', habilidades: 'Canalizar reparos, Chassi, Criatura artificial, Espírito elemental, Sem origem' },
    { name: 'Hynne', attrAjust: 'Destreza +4, Carisma +2, Força –2', habilidades: 'Arremessador, pequeno e rechonchudo, sorte salvadora' },
    { name: 'Kliren', attrAjust: 'Inteligência +4, Carisma +2, Força –2', habilidades: 'Híbrido, Lógica gnômica, Ossos frágeis, Vanguardista' },
    { name: 'Medusa', attrAjust: 'Destreza +4, Carisma +2', habilidades: 'Cria de megalokk, Natureza venenosa, Olhar atordoante' },
    { name: 'Osteon', attrAjust: '+2 em Três Atributos Diferentes (exceto Constituição), Constituição –2', habilidades: 'Armadura óssea, Memória póstuma, Natureza esquelética, Preço da não vida' },
    { name: 'Sereia/tritão', attrAjust: '+2 em Três Atributos Diferentes', habilidades: 'Canção dos mares, Mestre do tridente, Transformação anfíbia' },
    { name: 'Sílfide', attrAjust: 'Carisma +4, Destreza +2, Força –4', habilidades: 'Asas de borboleta, Espírito da natureza, Magia das fadas' },
    { name: 'Suraggel', attrAjust: 'Sabedoria +4, Carisma +2 (Aggelus); Destreza +4, Inteligência +2 (Sulfure)', habilidades: 'Herança divina, Luz sagrada (aggelus), Sombras profanas (sulfure)' },
    { name: 'Trog', attrAjust: 'Constituição +4, Força +2, Inteligência –2', habilidades: 'Mau cheiro, Mordida, Reptiliano, Sangue frio' },
]